### ISSUE TITLE
support for exact array sizes

### ISSUE THREAD

**Issue by mreinstein** [mikolalysenko/typedarray-pool#5]
some APIs will operate on an entire array, and the length needs to be exact. The adjusted API could look like:

```javascript
var pool = require("typedarray-pool")

// Allocate a buffer of 93 bytes
var exactSize = true
var f = pool.malloc(93, "uint8", exactSize)

// f.byteLength === 93

// When done, release buffer
pool.free(f)
```

`exactSize` would default to false, to avoid breaking the existing API.

@mikolalysenko would you be open to a PR  for this?

**Comment by mreinstein** [comment]
I'm still keen to write this if there's a willingness to merge it

**Comment by mikolalysenko** [comment]
👍

**Comment by mreinstein** [comment]
@mikolalysenko I have a PR that is just about ready for this, but I have several questions, which overlap some of the other issues in this tracker. Would you be available to chat on slack or some other more real-time medium? Probably faster than going back and forth in github messaging.
